// ------------------------------------------------------------------ //
// Theme registry for the Premier League club checkout replica.
//
// One entry per 2025/26 Premier League club except Tottenham (the
// original this component replicates). Each entry is a pure token bag:
// index.js turns it into CSS custom properties on the component root,
// and index.css only ever reads the variables. Adding a 20th club means
// adding an object here and an option in package.json's `club` picklist
// — no CSS or JSX changes.
//
// Colours are the clubs' primary/secondary identity colours. `onPrimary`
// is the ink that sits on top of `primary` and has to be set by hand —
// the light primaries (Leeds, Wolves, Man City) need dark ink.
//
// planName / price are representative membership scheme names and
// prices for demo purposes, not scraped from each club's live shop.
// Override per page with the planName / price props.
// ------------------------------------------------------------------ //

const BASE = {
  surface: "#ffffff",
  surfaceAlt: "#f6f7f9",
  text: "#14161a",
  muted: "#5d6470",
  border: "#dfe3e8",
  radius: "6px",
  body: "'Inter', system-ui, sans-serif",
  display: "'Archivo', system-ui, sans-serif",
  displayWeight: "700",
  displayTransform: "none",
  displaySpacing: "-0.01em",
  fee: "1.50",
  ddDiscount: "5",
  planDescription: "Adult (18+ Born before 1 August 2008)",
}

// A condensed/uppercase display treatment, used by the clubs whose own
// brand type is a tall condensed face.
const CONDENSED = {
  displayWeight: "400",
  displayTransform: "uppercase",
  displaySpacing: "0.01em",
}

const club = (entry) => {
  const merged = { ...BASE, ...entry }
  if (!merged.btnRadius) merged.btnRadius = merged.radius
  return merged
}

export const CLUBS = {
  // From the live /membership/red markup:
  //   #D80026  thead background, benefit links, JOIN NOW button
  //   #B50020  button hover      #1E252D  tfoot panel
  //   #F5F5F5  table ground      #E0E0E0  row borders
  //   buttons: border-radius 50px, uppercase 700, letter-spacing 2px
  //   headings: uppercase, font-weight 800, letter-spacing 2px
  //   tfoot price: £38 "Per Season"
  arsenal: club({
    name: "Arsenal",
    fullName: "Arsenal Football Club",
    initials: "AFC",
    site: "https://www.arsenal.com",
    primary: "#d80026",
    onPrimary: "#ffffff",
    secondary: "#1e252d",
    accent: "#d80026",
    onAccent: "#ffffff",
    surfaceAlt: "#f5f5f5",
    border: "#e0e0e0",
    display: "'Archivo', system-ui, sans-serif",
    body: "'Inter', system-ui, sans-serif",
    displayWeight: "800",
    displayTransform: "uppercase",
    displaySpacing: "0.09em",
    radius: "2px",
    btnRadius: "50px",
    stadium: {
      name: "Emirates Stadium",
      address1: "Emirates Stadium",
      address2: "Hornsey Road",
      city: "London",
      postalCode: "N7 7AJ",
    },
    planName: "Red Membership",
    planDescription: "Adult (18+)",
    price: "38.00",
  }),
  "aston-villa": club({
    name: "Aston Villa",
    fullName: "Aston Villa Football Club",
    initials: "AVFC",
    site: "https://www.avfc.co.uk",
    primary: "#670e36",
    onPrimary: "#ffffff",
    secondary: "#95bfe5",
    accent: "#95bfe5",
    onAccent: "#670e36",
    display: "'Oswald', system-ui, sans-serif",
    body: "'Barlow', system-ui, sans-serif",
    ...CONDENSED,
    displayWeight: "600",
    radius: "4px",
    stadium: {
      name: "Villa Park",
      address1: "Villa Park",
      address2: "Trinity Road",
      city: "Birmingham",
      postalCode: "B6 6HE",
    },
    planName: "Adult Villa Membership",
    price: "35.00",
  }),
  // Themed from the live afcb.co.uk memberships page markup:
  //   --primary-800: 92 0 17          -> #5C0011
  //   class="page bg-surface" + dark + !text-neutral-50  -> dark scheme
  //   headings: font-heading font-bold + uppercase
  //   buttons:  no rounding class     -> square corners
  //   body copy: "£3 transaction fee will be added per purchase"
  bournemouth: club({
    name: "AFC Bournemouth",
    fullName: "AFC Bournemouth",
    initials: "AFCB",
    site: "https://www.afcb.co.uk",
    scheme: "dark",
    primary: "#da291c",
    onPrimary: "#ffffff",
    secondary: "#5c0011",
    accent: "#da291c",
    onAccent: "#ffffff",
    surface: "#0f0f11",
    surfaceAlt: "#1a181c",
    text: "#fafafa",
    muted: "#a1a1aa",
    border: "#2c2c33",
    display: "'Archivo', system-ui, sans-serif",
    body: "'Inter', system-ui, sans-serif",
    displayWeight: "800",
    displayTransform: "uppercase",
    displaySpacing: "0.01em",
    radius: "0px",
    fee: "3.00",
    stadium: {
      name: "Vitality Stadium",
      address1: "Vitality Stadium",
      address2: "Dean Court, Kings Park",
      city: "Bournemouth",
      postalCode: "BH7 7AF",
    },
    planName: "Adult Cherries Membership",
    price: "30.00",
  }),
  // From the live /en/memberships-2026-27 page. That page is class-driven
  // (--red / --darkRed / --lightGrey) and exposes no hex values, so the
  // colours below are Brentford's brand red plus a dark red for the
  // darkRed blocks — the page confirms the palette structure, not the
  // exact values. Plan name, age tag and price are straight from the
  // membership card: Adult, "For ages 25+", £45.45 / SEASON.
  brentford: club({
    name: "Brentford",
    fullName: "Brentford Football Club",
    initials: "BFC",
    site: "https://www.brentfordfc.com",
    primary: "#e30613",
    onPrimary: "#ffffff",
    secondary: "#a30410",
    accent: "#e30613",
    onAccent: "#ffffff",
    surfaceAlt: "#f2f2f2",
    display: "'Rubik', system-ui, sans-serif",
    body: "'Rubik', system-ui, sans-serif",
    radius: "4px",
    stadium: {
      name: "Gtech Community Stadium",
      address1: "Gtech Community Stadium",
      address2: "166 Lionel Road South",
      city: "Brentford",
      postalCode: "TW8 0RU",
    },
    planName: "Adult Membership",
    planDescription: "For ages 25+",
    price: "45.45",
  }),
  brighton: club({
    name: "Brighton & Hove Albion",
    fullName: "Brighton & Hove Albion Football Club",
    initials: "BHA",
    site: "https://www.brightonandhovealbion.com",
    primary: "#004899",
    onPrimary: "#ffffff",
    secondary: "#42e1ae",
    accent: "#42e1ae",
    onAccent: "#1f1f1f",
    display: "'Montserrat', system-ui, sans-serif",
    body: "'Source Sans 3', 'Source Sans Pro', system-ui, sans-serif",
    displayWeight: "700",
    displayTransform: "uppercase",
    displaySpacing: "0.01em",
    radius: "3px",
    fee: "0.00",
    stadium: {
      name: "American Express Stadium",
      address1: "American Express Stadium",
      address2: "Village Way, Falmer",
      city: "Brighton",
      postalCode: "BN1 9BL",
    },
    planName: "MyAlbion+ Adult (UK)",
    planDescription: "Membership until 31/05/2027",
    price: "42.00",
  }),
  burnley: club({
    name: "Burnley",
    fullName: "Burnley Football Club",
    initials: "BFC",
    site: "https://www.burnleyfootballclub.com",
    primary: "#6c1d45",
    onPrimary: "#ffffff",
    secondary: "#99d6ea",
    accent: "#99d6ea",
    onAccent: "#6c1d45",
    display: "'Oswald', system-ui, sans-serif",
    body: "'Barlow', system-ui, sans-serif",
    ...CONDENSED,
    displayWeight: "600",
    radius: "4px",
    stadium: {
      name: "Turf Moor",
      address1: "Turf Moor",
      address2: "Harry Potts Way",
      city: "Burnley",
      postalCode: "BB10 4BX",
    },
    planName: "Adult Clarets Membership",
    price: "30.00",
  }),
  chelsea: club({
    name: "Chelsea",
    fullName: "Chelsea Football Club",
    initials: "CFC",
    site: "https://www.chelseafc.com",
    primary: "#034694",
    onPrimary: "#ffffff",
    secondary: "#dba111",
    accent: "#dba111",
    onAccent: "#0a1a2f",
    display: "'Archivo', system-ui, sans-serif",
    body: "'Inter', system-ui, sans-serif",
    radius: "4px",
    stadium: {
      name: "Stamford Bridge",
      address1: "Stamford Bridge",
      address2: "Fulham Road",
      city: "London",
      postalCode: "SW6 1HS",
    },
    planName: "Adult True Blue Membership",
    price: "45.00",
  }),
  "crystal-palace": club({
    name: "Crystal Palace",
    fullName: "Crystal Palace Football Club",
    initials: "CPFC",
    site: "https://www.cpfc.co.uk",
    primary: "#1b458f",
    onPrimary: "#ffffff",
    secondary: "#c4122e",
    accent: "#c4122e",
    onAccent: "#ffffff",
    display: "'Saira Condensed', system-ui, sans-serif",
    body: "'Inter', system-ui, sans-serif",
    ...CONDENSED,
    displayWeight: "700",
    radius: "4px",
    stadium: {
      name: "Selhurst Park",
      address1: "Selhurst Park",
      address2: "Holmesdale Road",
      city: "London",
      postalCode: "SE25 6PU",
    },
    planName: "Adult Eagles Membership",
    price: "35.00",
  }),
  everton: club({
    name: "Everton",
    fullName: "Everton Football Club",
    initials: "EFC",
    site: "https://www.evertonfc.com",
    primary: "#003399",
    onPrimary: "#ffffff",
    secondary: "#ffffff",
    accent: "#2f56b5",
    onAccent: "#ffffff",
    display: "'Archivo', system-ui, sans-serif",
    body: "'Inter', system-ui, sans-serif",
    radius: "4px",
    stadium: {
      name: "Hill Dickinson Stadium",
      address1: "Hill Dickinson Stadium",
      address2: "Regent Road, Bramley-Moore Dock",
      city: "Liverpool",
      postalCode: "L3 0BW",
    },
    planName: "Adult Toffees Membership",
    price: "35.00",
  }),
  fulham: club({
    name: "Fulham",
    fullName: "Fulham Football Club",
    initials: "FFC",
    site: "https://www.fulhamfc.com",
    primary: "#000000",
    onPrimary: "#ffffff",
    secondary: "#cc0000",
    accent: "#cc0000",
    onAccent: "#ffffff",
    display: "'Manrope', system-ui, sans-serif",
    body: "'Manrope', system-ui, sans-serif",
    radius: "2px",
    stadium: {
      name: "Craven Cottage",
      address1: "Craven Cottage",
      address2: "Stevenage Road",
      city: "London",
      postalCode: "SW6 6HH",
    },
    planName: "Adult Cottagers Membership",
    price: "35.00",
  }),
  leeds: club({
    name: "Leeds United",
    fullName: "Leeds United Football Club",
    initials: "LUFC",
    site: "https://www.leedsunited.com",
    primary: "#ffcd00",
    onPrimary: "#1d428a",
    secondary: "#1d428a",
    accent: "#1d428a",
    onAccent: "#ffffff",
    display: "'Bebas Neue', system-ui, sans-serif",
    body: "'Inter', system-ui, sans-serif",
    ...CONDENSED,
    displaySpacing: "0.03em",
    radius: "0px",
    stadium: {
      name: "Elland Road",
      address1: "Elland Road",
      address2: "Elland Road",
      city: "Leeds",
      postalCode: "LS11 0ES",
    },
    planName: "Adult Whites Membership",
    price: "35.00",
  }),
  liverpool: club({
    name: "Liverpool",
    fullName: "Liverpool Football Club",
    initials: "LFC",
    site: "https://www.liverpoolfc.com",
    primary: "#c8102e",
    onPrimary: "#ffffff",
    secondary: "#00b2a9",
    accent: "#00b2a9",
    onAccent: "#0a1a2f",
    display: "'Archivo', system-ui, sans-serif",
    body: "'Inter', system-ui, sans-serif",
    radius: "4px",
    stadium: {
      name: "Anfield",
      address1: "Anfield",
      address2: "Anfield Road",
      city: "Liverpool",
      postalCode: "L4 0TH",
    },
    planName: "Adult Official Membership",
    price: "40.00",
  }),
  "man-city": club({
    name: "Manchester City",
    fullName: "Manchester City Football Club",
    initials: "MCFC",
    site: "https://www.mancity.com",
    primary: "#6cabdd",
    onPrimary: "#1c2c5b",
    secondary: "#1c2c5b",
    accent: "#1c2c5b",
    onAccent: "#ffffff",
    display: "'Archivo', system-ui, sans-serif",
    body: "'Inter', system-ui, sans-serif",
    radius: "8px",
    stadium: {
      name: "Etihad Stadium",
      address1: "Etihad Stadium",
      address2: "Etihad Campus, Ashton New Road",
      city: "Manchester",
      postalCode: "M11 3FF",
    },
    planName: "Adult Cityzens Matchday Membership",
    price: "45.00",
  }),
  "man-utd": club({
    name: "Manchester United",
    fullName: "Manchester United Football Club",
    initials: "MUFC",
    site: "https://www.manutd.com",
    primary: "#da291c",
    onPrimary: "#ffffff",
    secondary: "#000000",
    accent: "#fbe122",
    onAccent: "#000000",
    display: "'Archivo', system-ui, sans-serif",
    body: "'Inter', system-ui, sans-serif",
    radius: "2px",
    stadium: {
      name: "Old Trafford",
      address1: "Old Trafford",
      address2: "Sir Matt Busby Way, Stretford",
      city: "Manchester",
      postalCode: "M16 0RA",
    },
    planName: "Adult Official Membership",
    price: "40.00",
  }),
  newcastle: club({
    name: "Newcastle United",
    fullName: "Newcastle United Football Club",
    initials: "NUFC",
    site: "https://www.nufc.co.uk",
    primary: "#241f20",
    onPrimary: "#ffffff",
    secondary: "#ffffff",
    accent: "#41b6e6",
    onAccent: "#241f20",
    display: "'Oswald', system-ui, sans-serif",
    body: "'Inter', system-ui, sans-serif",
    ...CONDENSED,
    displayWeight: "500",
    radius: "2px",
    stadium: {
      name: "St James' Park",
      address1: "St James' Park",
      address2: "Barrack Road",
      city: "Newcastle upon Tyne",
      postalCode: "NE1 4ST",
    },
    planName: "Adult Magpies Membership",
    price: "35.00",
  }),
  // Norwich are Championship, not Premier League — added for a specific
  // mockup. Themed from their live tickets.canaries.co.uk memberships page:
  //   #003E14  .landing-button.primary2 / .header / comparison block
  //   #F6D716  ticks, comp-price, bg-divider text, focus outline
  //   "KippaxCondensed", Helvetica, Arial  font-weight 700, uppercase
  //   border-radius: 4px on .landing-button
  //   basket: City Membership £29.00, TotalCommissions £0.00
  // KippaxCondensed is licensed to the club; Barlow Condensed 700 is the
  // closest Google face. Swap it per page with the displayFont prop.
  norwich: club({
    name: "Norwich City",
    fullName: "Norwich City Football Club",
    initials: "NCFC",
    site: "https://www.canaries.co.uk",
    primary: "#003e14",
    onPrimary: "#ffffff",
    secondary: "#f6d716",
    accent: "#f6d716",
    onAccent: "#003e14",
    display: "'Barlow Condensed', system-ui, sans-serif",
    body: "'Inter', system-ui, sans-serif",
    displayWeight: "700",
    displayTransform: "uppercase",
    displaySpacing: "0.01em",
    radius: "4px",
    fee: "0.00",
    stadium: {
      name: "Carrow Road",
      address1: "Carrow Road",
      address2: "Carrow Road",
      city: "Norwich",
      postalCode: "NR1 1JE",
    },
    planName: "City Membership",
    planDescription: "Membership until 30/06/2027",
    price: "29.00",
  }),
  "nottm-forest": club({
    name: "Nottingham Forest",
    fullName: "Nottingham Forest Football Club",
    initials: "NFFC",
    site: "https://www.nottinghamforest.co.uk",
    primary: "#dd0000",
    onPrimary: "#ffffff",
    secondary: "#ffffff",
    accent: "#1a1a1a",
    onAccent: "#ffffff",
    display: "'Teko', system-ui, sans-serif",
    body: "'Inter', system-ui, sans-serif",
    ...CONDENSED,
    displayWeight: "600",
    displaySpacing: "0.02em",
    radius: "4px",
    stadium: {
      name: "The City Ground",
      address1: "The City Ground",
      address2: "Pavilion Road, West Bridgford",
      city: "Nottingham",
      postalCode: "NG2 5FJ",
    },
    planName: "Adult Reds Membership",
    price: "30.00",
  }),
  sunderland: club({
    name: "Sunderland",
    fullName: "Sunderland Association Football Club",
    initials: "SAFC",
    site: "https://www.safc.com",
    primary: "#eb172b",
    onPrimary: "#ffffff",
    secondary: "#211e1f",
    accent: "#211e1f",
    onAccent: "#ffffff",
    display: "'Barlow Condensed', system-ui, sans-serif",
    body: "'Barlow', system-ui, sans-serif",
    ...CONDENSED,
    displayWeight: "700",
    radius: "4px",
    stadium: {
      name: "Stadium of Light",
      address1: "Stadium of Light",
      address2: "Millennium Way, Monkwearmouth",
      city: "Sunderland",
      postalCode: "SR5 1SU",
    },
    planName: "Adult Black Cats Membership",
    price: "30.00",
  }),
  "west-ham": club({
    name: "West Ham United",
    fullName: "West Ham United Football Club",
    initials: "WHU",
    site: "https://www.whufc.com",
    primary: "#7a263a",
    onPrimary: "#ffffff",
    secondary: "#1bb1e7",
    accent: "#1bb1e7",
    onAccent: "#0a1a2f",
    display: "'Archivo', system-ui, sans-serif",
    body: "'Inter', system-ui, sans-serif",
    radius: "4px",
    stadium: {
      name: "London Stadium",
      address1: "London Stadium",
      address2: "Queen Elizabeth Olympic Park",
      city: "London",
      postalCode: "E20 2ST",
    },
    planName: "Adult Hammers Membership",
    price: "35.00",
  }),
  wolves: club({
    name: "Wolves",
    fullName: "Wolverhampton Wanderers Football Club",
    initials: "WWFC",
    site: "https://www.wolves.co.uk",
    primary: "#fdb913",
    onPrimary: "#231f20",
    secondary: "#231f20",
    accent: "#231f20",
    onAccent: "#fdb913",
    display: "'Bebas Neue', system-ui, sans-serif",
    body: "'Inter', system-ui, sans-serif",
    ...CONDENSED,
    displaySpacing: "0.03em",
    radius: "0px",
    stadium: {
      name: "Molineux Stadium",
      address1: "Molineux Stadium",
      address2: "Waterloo Road",
      city: "Wolverhampton",
      postalCode: "WV1 4QR",
    },
    planName: "Adult Pack Membership",
    price: "30.00",
  }),
}

export const DEFAULT_CLUB = "arsenal"

export const getClub = (id) => CLUBS[id] || CLUBS[DEFAULT_CLUB]
