// ------------------------------------------------------------------ //
// Theme registry for the Premier League club checkout replica.
//
// One entry per 2025/26 Premier League club except Tottenham (the
// original this component replicates). Each entry is a pure token bag:
// index.js turns it into CSS custom properties on the component root,
// and index.css only ever reads the variables. Adding a 20th club means
// adding an object here and an option in package.json's `club` picklist
// — no CSS or JSX changes.
//
// Colours are the clubs' primary/secondary identity colours. `onPrimary`
// is the ink that sits on top of `primary` and has to be set by hand —
// the light primaries (Leeds, Wolves, Man City) need dark ink.
//
// planName / price are representative membership scheme names and
// prices for demo purposes, not scraped from each club's live shop.
// Override per page with the planName / price props.
// ------------------------------------------------------------------ //

const BASE = {
  surface: "#ffffff",
  surfaceAlt: "#f6f7f9",
  text: "#14161a",
  muted: "#5d6470",
  border: "#dfe3e8",
  radius: "6px",
  body: "'Inter', system-ui, sans-serif",
  display: "'Archivo', system-ui, sans-serif",
  displayWeight: "700",
  displayTransform: "none",
  displaySpacing: "-0.01em",
  fee: "1.50",
  ddDiscount: "5",
  planDescription: "Adult (18+ Born before 1 August 2008)",
}

// A condensed/uppercase display treatment, used by the clubs whose own
// brand type is a tall condensed face.
const CONDENSED = {
  displayWeight: "400",
  displayTransform: "uppercase",
  displaySpacing: "0.01em",
}

const club = (entry) => ({ ...BASE, ...entry })

export const CLUBS = {
  arsenal: club({
    name: "Arsenal",
    fullName: "Arsenal Football Club",
    initials: "AFC",
    site: "https://www.arsenal.com",
    primary: "#ef0107",
    onPrimary: "#ffffff",
    secondary: "#063672",
    accent: "#9c824a",
    onAccent: "#ffffff",
    display: "'Archivo', system-ui, sans-serif",
    body: "'Inter', system-ui, sans-serif",
    radius: "2px",
    planName: "Adult Red Membership",
    price: "40.00",
  }),
  "aston-villa": club({
    name: "Aston Villa",
    fullName: "Aston Villa Football Club",
    initials: "AVFC",
    site: "https://www.avfc.co.uk",
    primary: "#670e36",
    onPrimary: "#ffffff",
    secondary: "#95bfe5",
    accent: "#95bfe5",
    onAccent: "#670e36",
    display: "'Oswald', system-ui, sans-serif",
    body: "'Barlow', system-ui, sans-serif",
    ...CONDENSED,
    displayWeight: "600",
    radius: "4px",
    planName: "Adult Villa Membership",
    price: "35.00",
  }),
  bournemouth: club({
    name: "AFC Bournemouth",
    fullName: "AFC Bournemouth",
    initials: "AFCB",
    site: "https://www.afcb.co.uk",
    primary: "#da291c",
    onPrimary: "#ffffff",
    secondary: "#000000",
    accent: "#000000",
    onAccent: "#ffffff",
    display: "'Barlow Condensed', system-ui, sans-serif",
    body: "'Barlow', system-ui, sans-serif",
    ...CONDENSED,
    displayWeight: "700",
    radius: "4px",
    planName: "Adult Cherries Membership",
    price: "30.00",
  }),
  brentford: club({
    name: "Brentford",
    fullName: "Brentford Football Club",
    initials: "BFC",
    site: "https://www.brentfordfc.com",
    primary: "#e30613",
    onPrimary: "#ffffff",
    secondary: "#140e0c",
    accent: "#fbb800",
    onAccent: "#140e0c",
    display: "'Rubik', system-ui, sans-serif",
    body: "'Rubik', system-ui, sans-serif",
    radius: "8px",
    planName: "Adult Bees Membership",
    price: "35.00",
  }),
  brighton: club({
    name: "Brighton & Hove Albion",
    fullName: "Brighton & Hove Albion Football Club",
    initials: "BHA",
    site: "https://www.brightonandhovealbion.com",
    primary: "#0057b8",
    onPrimary: "#ffffff",
    secondary: "#ffcd00",
    accent: "#ffcd00",
    onAccent: "#0057b8",
    display: "'Archivo', system-ui, sans-serif",
    body: "'Inter', system-ui, sans-serif",
    radius: "6px",
    planName: "Adult Albion Membership",
    price: "35.00",
  }),
  burnley: club({
    name: "Burnley",
    fullName: "Burnley Football Club",
    initials: "BFC",
    site: "https://www.burnleyfootballclub.com",
    primary: "#6c1d45",
    onPrimary: "#ffffff",
    secondary: "#99d6ea",
    accent: "#99d6ea",
    onAccent: "#6c1d45",
    display: "'Oswald', system-ui, sans-serif",
    body: "'Barlow', system-ui, sans-serif",
    ...CONDENSED,
    displayWeight: "600",
    radius: "4px",
    planName: "Adult Clarets Membership",
    price: "30.00",
  }),
  chelsea: club({
    name: "Chelsea",
    fullName: "Chelsea Football Club",
    initials: "CFC",
    site: "https://www.chelseafc.com",
    primary: "#034694",
    onPrimary: "#ffffff",
    secondary: "#dba111",
    accent: "#dba111",
    onAccent: "#0a1a2f",
    display: "'Archivo', system-ui, sans-serif",
    body: "'Inter', system-ui, sans-serif",
    radius: "4px",
    planName: "Adult True Blue Membership",
    price: "45.00",
  }),
  "crystal-palace": club({
    name: "Crystal Palace",
    fullName: "Crystal Palace Football Club",
    initials: "CPFC",
    site: "https://www.cpfc.co.uk",
    primary: "#1b458f",
    onPrimary: "#ffffff",
    secondary: "#c4122e",
    accent: "#c4122e",
    onAccent: "#ffffff",
    display: "'Saira Condensed', system-ui, sans-serif",
    body: "'Inter', system-ui, sans-serif",
    ...CONDENSED,
    displayWeight: "700",
    radius: "4px",
    planName: "Adult Eagles Membership",
    price: "35.00",
  }),
  everton: club({
    name: "Everton",
    fullName: "Everton Football Club",
    initials: "EFC",
    site: "https://www.evertonfc.com",
    primary: "#003399",
    onPrimary: "#ffffff",
    secondary: "#ffffff",
    accent: "#2f56b5",
    onAccent: "#ffffff",
    display: "'Archivo', system-ui, sans-serif",
    body: "'Inter', system-ui, sans-serif",
    radius: "4px",
    planName: "Adult Toffees Membership",
    price: "35.00",
  }),
  fulham: club({
    name: "Fulham",
    fullName: "Fulham Football Club",
    initials: "FFC",
    site: "https://www.fulhamfc.com",
    primary: "#000000",
    onPrimary: "#ffffff",
    secondary: "#cc0000",
    accent: "#cc0000",
    onAccent: "#ffffff",
    display: "'Manrope', system-ui, sans-serif",
    body: "'Manrope', system-ui, sans-serif",
    radius: "2px",
    planName: "Adult Cottagers Membership",
    price: "35.00",
  }),
  leeds: club({
    name: "Leeds United",
    fullName: "Leeds United Football Club",
    initials: "LUFC",
    site: "https://www.leedsunited.com",
    primary: "#ffcd00",
    onPrimary: "#1d428a",
    secondary: "#1d428a",
    accent: "#1d428a",
    onAccent: "#ffffff",
    display: "'Bebas Neue', system-ui, sans-serif",
    body: "'Inter', system-ui, sans-serif",
    ...CONDENSED,
    displaySpacing: "0.03em",
    radius: "0px",
    planName: "Adult Whites Membership",
    price: "35.00",
  }),
  liverpool: club({
    name: "Liverpool",
    fullName: "Liverpool Football Club",
    initials: "LFC",
    site: "https://www.liverpoolfc.com",
    primary: "#c8102e",
    onPrimary: "#ffffff",
    secondary: "#00b2a9",
    accent: "#00b2a9",
    onAccent: "#0a1a2f",
    display: "'Archivo', system-ui, sans-serif",
    body: "'Inter', system-ui, sans-serif",
    radius: "4px",
    planName: "Adult Official Membership",
    price: "40.00",
  }),
  "man-city": club({
    name: "Manchester City",
    fullName: "Manchester City Football Club",
    initials: "MCFC",
    site: "https://www.mancity.com",
    primary: "#6cabdd",
    onPrimary: "#1c2c5b",
    secondary: "#1c2c5b",
    accent: "#1c2c5b",
    onAccent: "#ffffff",
    display: "'Archivo', system-ui, sans-serif",
    body: "'Inter', system-ui, sans-serif",
    radius: "8px",
    planName: "Adult Cityzens Matchday Membership",
    price: "45.00",
  }),
  "man-utd": club({
    name: "Manchester United",
    fullName: "Manchester United Football Club",
    initials: "MUFC",
    site: "https://www.manutd.com",
    primary: "#da291c",
    onPrimary: "#ffffff",
    secondary: "#000000",
    accent: "#fbe122",
    onAccent: "#000000",
    display: "'Archivo', system-ui, sans-serif",
    body: "'Inter', system-ui, sans-serif",
    radius: "2px",
    planName: "Adult Official Membership",
    price: "40.00",
  }),
  newcastle: club({
    name: "Newcastle United",
    fullName: "Newcastle United Football Club",
    initials: "NUFC",
    site: "https://www.nufc.co.uk",
    primary: "#241f20",
    onPrimary: "#ffffff",
    secondary: "#ffffff",
    accent: "#41b6e6",
    onAccent: "#241f20",
    display: "'Oswald', system-ui, sans-serif",
    body: "'Inter', system-ui, sans-serif",
    ...CONDENSED,
    displayWeight: "500",
    radius: "2px",
    planName: "Adult Magpies Membership",
    price: "35.00",
  }),
  "nottm-forest": club({
    name: "Nottingham Forest",
    fullName: "Nottingham Forest Football Club",
    initials: "NFFC",
    site: "https://www.nottinghamforest.co.uk",
    primary: "#dd0000",
    onPrimary: "#ffffff",
    secondary: "#ffffff",
    accent: "#1a1a1a",
    onAccent: "#ffffff",
    display: "'Teko', system-ui, sans-serif",
    body: "'Inter', system-ui, sans-serif",
    ...CONDENSED,
    displayWeight: "600",
    displaySpacing: "0.02em",
    radius: "4px",
    planName: "Adult Reds Membership",
    price: "30.00",
  }),
  sunderland: club({
    name: "Sunderland",
    fullName: "Sunderland Association Football Club",
    initials: "SAFC",
    site: "https://www.safc.com",
    primary: "#eb172b",
    onPrimary: "#ffffff",
    secondary: "#211e1f",
    accent: "#211e1f",
    onAccent: "#ffffff",
    display: "'Barlow Condensed', system-ui, sans-serif",
    body: "'Barlow', system-ui, sans-serif",
    ...CONDENSED,
    displayWeight: "700",
    radius: "4px",
    planName: "Adult Black Cats Membership",
    price: "30.00",
  }),
  "west-ham": club({
    name: "West Ham United",
    fullName: "West Ham United Football Club",
    initials: "WHU",
    site: "https://www.whufc.com",
    primary: "#7a263a",
    onPrimary: "#ffffff",
    secondary: "#1bb1e7",
    accent: "#1bb1e7",
    onAccent: "#0a1a2f",
    display: "'Archivo', system-ui, sans-serif",
    body: "'Inter', system-ui, sans-serif",
    radius: "4px",
    planName: "Adult Hammers Membership",
    price: "35.00",
  }),
  wolves: club({
    name: "Wolves",
    fullName: "Wolverhampton Wanderers Football Club",
    initials: "WWFC",
    site: "https://www.wolves.co.uk",
    primary: "#fdb913",
    onPrimary: "#231f20",
    secondary: "#231f20",
    accent: "#231f20",
    onAccent: "#fdb913",
    display: "'Bebas Neue', system-ui, sans-serif",
    body: "'Inter', system-ui, sans-serif",
    ...CONDENSED,
    displaySpacing: "0.03em",
    radius: "0px",
    planName: "Adult Pack Membership",
    price: "30.00",
  }),
}

export const DEFAULT_CLUB = "arsenal"

export const getClub = (id) => CLUBS[id] || CLUBS[DEFAULT_CLUB]
